Step3-kakao-tech-campus/Team7_BE

src/main/java/com/example/tily/user/User.java
src/main/java/com/example/tily/user/UserController.java
src/main/java/com/example/tily/user/UserRequest.java
src/main/java/com/example/tily/user/UserService.java
src/main/resources/application.yml
src/main/resources/data.sql
src/test/java/com/example/tily/user/UserControllerTest.java

로그인 기능 구현했습니다. 
-  [x] 로그인 기능 구현
-  [x] 비밀번호 재설정 기능
-  [x] 테스트 코드 작성 
지금은 그냥 임시로 h2에 tngus@pusan.ac.kr 사용자 넣어두고 test 진행했습니다. 테스트 코드 작성 쪽 공부가 필요할 것 같네요..
closes #10

로그인 기능 구현 

---

src/main/java/com/example/tily/TiLyApplication.java
src/main/java/com/example/tily/til/Til.java
src/main/java/com/example/tily/til/TilController.java
src/main/java/com/example/tily/til/TilRepository.java
src/main/java/com/example/tily/til/TilRequest.java
src/main/java/com/example/tily/til/TilResponse.java
src/main/java/com/example/tily/til/TilService.java
src/main/resources/data.sql
src/test/java/com/example/tily/til/TilControllerTest.java

TIL CRUD 기능을 구현
-   [x] TIL 조회 구현
-   [x] TIL 수정(저장) 구현
-   [x] TIL 삭제 구현
-   [x] TIL 제출 구현
closes (#26)

TIL CRUD 기능 구현

---

src/main/java/com/example/tily/TiLyApplication.java
src/test/java/com/example/tily/til/TilControllerTest.java
src/test/java/com/example/tily/util/DummyEntity.java

Category의 자료형을 변경하고 테스트 코드와 더미데이터에서 나타나는 문제를 수정함
-   [x] Category의 자료형을 변경
-   [x]  테스트 코드와 더미데이터에서 나타나는 문제를 수정

카테고리 자료형 수정과 관련 코드 수정

---

src/main/java/com/example/tily/TiLyApplication.java
src/main/java/com/example/tily/til/Til.java
src/main/java/com/example/tily/til/TilController.java
src/main/java/com/example/tily/til/TilRequest.java
src/main/java/com/example/tily/til/TilService.java
src/test/java/com/example/tily/til/TilControllerTest.java

TIL 제출 시 제출일자를 추가한다.
-   [x] Request에 submitDate 추가
-   [x] 더미데이터 newTil의 isPersonal 수정
-   [x] TIL 제출 테스트코드 수정

TIL 제출 시 제출일자 추가

---

src/main/java/com/example/tily/TiLyApplication.java
src/main/java/com/example/tily/roadmap/RoadmapController.java
src/main/java/com/example/tily/step/Step.java
src/main/java/com/example/tily/til/Til.java
src/main/java/com/example/tily/til/TilController.java
src/main/java/com/example/tily/til/TilRepository.java
src/main/java/com/example/tily/til/TilResponse.java
src/main/java/com/example/tily/til/TilService.java
src/test/java/com/example/tily/til/TilControllerTest.java

파라미터를 사용해 나의 til 목록 조회하기 기능을 구현했습니다.
til 엔티티에서 roadmap, step, user와 매핑을 설정하고, step에서 UserStep 참조를 삭제했습니다. (단방향으로)
closes #36

나의 Til 목록 조회하기 기능

---

src/test/java/com/example/tily/roadmap/RoadmapControllerTest.java
src/test/java/com/example/tily/step/StepControllerTest.java
src/test/java/com/example/tily/til/TilControllerTest.java
src/test/java/com/example/tily/user/UserControllerTest.java

더미 데이터에 맞춰 데스트 코드 수정했습니다. 
-   [x] 테스트 코드 수정

test : 더미 데이터에 맞춰 테스트 코드 수정

---

src/main/java/com/example/tily/TiLyApplication.java
src/main/java/com/example/tily/alarm/Alarm.java
src/main/java/com/example/tily/alarm/AlarmController.java
src/main/java/com/example/tily/alarm/AlarmRepository.java
src/main/java/com/example/tily/alarm/AlarmRequest.java
src/main/java/com/example/tily/alarm/AlarmResponse.java
src/main/java/com/example/tily/alarm/AlarmService.java
src/main/java/com/example/tily/comment/Comment.java
src/main/java/com/example/tily/comment/CommentService.java
src/main/java/com/example/tily/til/TilResponse.java
src/main/java/com/example/tily/til/TilService.java
src/test/java/com/example/tily/Alarm/AlarmControllerTest.java
src/test/java/com/example/tily/util/DummyEntity.java

알림 조회 기능과 읽기 기능을 구현했습니다. 
알림 조회할 때는 최근순으로 정렬해서 보내달라고 하셔서 최근에 생성된 순서대로 정렬해서 보냈습니다. 
그리고 Til 조회 시 응답 DTO에 빠진 데이터와 형식을 수정했습니다. 
closes #61

알림 조회, 읽기 기능 구현 

---

src/main/java/com/example/tily/roadmap/RoadmapRequest.java
src/main/java/com/example/tily/roadmap/RoadmapService.java
src/test/java/com/example/tily/roadmap/RoadmapControllerTest.java

그룹 로드맵 생성하기 API에 dueDate를 추가함
-   [x] service, request 수정
-   [x] 테스트 코드 수정

dueDate 추가

---

src/main/java/com/example/tily/roadmap/RoadmapService.java

'로드맵의 구성원 전체 조회하기'의 권한을 변경함. (유저->매니저)
-   [x] 로드맵의 구성원 전체 조회하기 service 코드 수정

로드맵의 구성원 전체 조회하기 권한 변경

---

src/main/java/com/example/tily/user/UserResponse.java

/gardens api의 응답 중 day를 date로 수정
-   [ ] day -> date로 수정

/gardens day를 date로 수정

---

src/main/java/com/example/tily/_core/errors/exception/ExceptionCode.java
src/main/java/com/example/tily/user/User.java
src/main/java/com/example/tily/user/UserController.java
src/main/java/com/example/tily/user/UserRequest.java
src/main/java/com/example/tily/user/UserResponse.java
src/main/java/com/example/tily/user/UserService.java
src/main/resources/data.sql

user 정보 조회하기, 수정하기 api 구현했습니다. 
그리고 user 관련 코드 리팩토링 진행했습니다. 
closes #79 
closes #80

user 조회, 수정 기능 구현 및 리팩토링 

---

src/main/java/com/example/tily/roadmap/RoadmapResponse.java
src/main/java/com/example/tily/roadmap/RoadmapService.java

findRoadmapMember에 myRole 추가함 (동영님 요구)

findRoadmapMember에 myRole 추가

---

src/main/java/com/example/tily/til/Til.java

til content 길이 수정

---

.gitignore
src/main/java/com/example/tily/_core/S3/S3Service.java
src/main/java/com/example/tily/_core/security/SecurityConfig.java
src/main/java/com/example/tily/alarm/AlarmRepository.java
src/main/java/com/example/tily/alarm/AlarmResponse.java
src/main/java/com/example/tily/comment/CommentService.java
src/main/java/com/example/tily/image/ImageController.java
src/main/java/com/example/tily/image/ImageService.java
src/main/java/com/example/tily/roadmap/RoadmapRequest.java
src/main/java/com/example/tily/roadmap/RoadmapService.java
src/main/java/com/example/tily/step/StepResponse.java
src/main/java/com/example/tily/step/StepService.java
src/main/java/com/example/tily/til/Til.java
src/main/java/com/example/tily/til/TilService.java
src/main/resources/application-local.yml
src/main/resources/application-prod.yml

S3를 구축하고, 프로젝트와 연동하고 테스트를 진행했습니다. 
access key 등 중요한 값들은 applicaion-secret.yml 에서 관리합니다. 
그리고 자잘자잘한 예외, 버그들을 수정했습니다. 
closes #97

S3 구축 및 연동

---

src/main/java/com/example/tily/roadmap/Roadmap.java
src/main/java/com/example/tily/roadmap/RoadmapRequest.java
src/main/java/com/example/tily/roadmap/RoadmapService.java
src/main/java/com/example/tily/step/Step.java
src/main/java/com/example/tily/step/StepController.java
src/main/java/com/example/tily/step/StepRequest.java
src/main/java/com/example/tily/step/StepResponse.java
src/main/java/com/example/tily/step/StepService.java
src/main/java/com/example/tily/step/reference/Reference.java
src/main/java/com/example/tily/step/reference/ReferenceController.java
src/main/java/com/example/tily/step/reference/ReferenceRequest.java
src/main/java/com/example/tily/step/reference/ReferenceService.java

roadmap 생성하기, 수정하기 api 수정된 것을 반영했습니다.
그에 따라 step 생성하기, 수정하기 api를 구현했습니다.
reference 생성하기 api를 구현하고 리팩토링을 진행했습니다. 
(step 삭제하기, reference 삭제하기 api는 한홍님이 구현할 예정입니다)
closes #114, #113

Reference , Step API 생성 및 수정

---

src/main/java/com/example/tily/comment/CommentController.java
src/main/java/com/example/tily/comment/CommentRequest.java
src/main/java/com/example/tily/comment/CommentService.java
src/main/java/com/example/tily/image/ImageController.java
src/main/java/com/example/tily/step/reference/ReferenceController.java
src/main/java/com/example/tily/step/reference/ReferenceRequest.java
src/main/java/com/example/tily/step/reference/ReferenceService.java

수정한 API에 맞게 Reference, Comment, Image 리팩토링함
-   [x] Reference 리팩토링
-   [x] Comment 리팩토링
-   [x] Image 리팩토링
closes(#120 )

Reference, Comment, Image API 수정

---

src/main/java/com/example/tily/roadmap/RoadmapController.java
src/main/java/com/example/tily/roadmap/RoadmapRequest.java
src/main/java/com/example/tily/roadmap/RoadmapService.java
src/main/java/com/example/tily/step/StepService.java
src/main/java/com/example/tily/user/socialLogin/SocialLoginController.java

Roadmap 생성 api 수정했습니다. 기존에는 개인 로드맵 생성 api와 그룹 로드맵 생성 api가 따로 있었지만, service 레이어에서 생성 로직이 거의 동일해 하나의 api로 처리했습니다.

Roadmap 생성 api 수정

---

src/main/java/com/example/tily/comment/CommentRepository.java
src/main/java/com/example/tily/comment/CommentService.java
src/main/java/com/example/tily/roadmap/RoadmapController.java
src/main/java/com/example/tily/roadmap/RoadmapRepository.java
src/main/java/com/example/tily/roadmap/RoadmapService.java
src/main/java/com/example/tily/roadmap/relation/UserRoadmap.java
src/main/java/com/example/tily/til/TilRepository.java
src/main/java/com/example/tily/til/TilService.java

SoftDelete 함수를 모두 JPQL로 변경하였고
그룹 로드맵 정보 수정하기 API를 @PostMapping -> @PatchMapping으로 수정

Soft delete 에러 수정 2

---

src/main/java/com/example/tily/user/UserService.java

smtp 사용 안함

---

src/main/java/com/example/tily/roadmap/RoadmapController.java
src/main/java/com/example/tily/roadmap/RoadmapService.java

'그룹 로드맵 정보 조회하기'를 토큰 없이 접근 할 수 있도록 수정함

'그룹 로드맵 정보 조회하기' 수정

---

src/main/java/com/example/tily/roadmap/RoadmapService.java
src/main/java/com/example/tily/roadmap/relation/UserRoadmap.java
src/main/java/com/example/tily/step/reference/ReferenceController.java
src/main/java/com/example/tily/step/reference/ReferenceRequest.java
src/main/java/com/example/tily/step/reference/ReferenceService.java

roadmap 생성 시 code와 isPublic 데이터 수정했습니다.
그리고 로드맵에서 구성원 강퇴시 role만 none으로 바뀌어서, isAccet도 false로 바꿨습니다.

roadmap 관련 api 수정

---

src/main/java/com/example/tily/alarm/AlarmRequest.java
src/main/java/com/example/tily/alarm/AlarmResponse.java
src/main/java/com/example/tily/comment/CommentRequest.java
src/main/java/com/example/tily/comment/CommentService.java
src/main/java/com/example/tily/roadmap/RoadmapResponse.java
src/main/java/com/example/tily/roadmap/RoadmapService.java
src/main/java/com/example/tily/step/StepResponse.java
src/main/java/com/example/tily/til/TilResponse.java
src/main/java/com/example/tily/user/UserResponse.java

BE  코드 컨벤션에 따른 리팩토링

---

src/main/java/com/example/tily/comment/CommentService.java
src/main/java/com/example/tily/roadmap/Roadmap.java
src/main/java/com/example/tily/roadmap/RoadmapController.java
src/main/java/com/example/tily/step/StepService.java
src/main/java/com/example/tily/til/Til.java
src/main/java/com/example/tily/til/TilResponse.java

댓글 작성 시 댓글 수 증가, step 생성 시 step 수 증가 버그 수정했습니다.
step 생성, 수정 시 마감 시간도 수정했습니다(9시간 더해서 저장)

댓글, step 수 버그 수정

---

src/main/java/com/example/tily/_core/S3/FileFolder.java
src/main/java/com/example/tily/_core/S3/S3Service.java
src/main/java/com/example/tily/_core/utils/ApiUtils.java
src/main/java/com/example/tily/alarm/AlarmController.java
src/main/java/com/example/tily/comment/CommentController.java
src/main/java/com/example/tily/image/ImageController.java
src/main/java/com/example/tily/roadmap/RoadmapController.java
src/main/java/com/example/tily/step/StepController.java
src/main/java/com/example/tily/step/reference/ReferenceController.java
src/main/java/com/example/tily/til/TilController.java
src/main/java/com/example/tily/user/UserController.java
src/main/java/com/example/tily/user/UserService.java
src/main/java/com/example/tily/user/socialLogin/SocialLoginController.java

성공 응답을 200만 사용하다가 200, 201로 처리한다

성공 응답 로직 리팩토링

---

src/main/java/com/example/tily/TiLyApplication.java
src/main/java/com/example/tily/_core/security/JwtAuthenticationFilter.java
src/main/java/com/example/tily/til/TilRepository.java

builder 버그 수정

---

src/main/java/com/example/tily/_core/security/JWTProvider.java
src/main/java/com/example/tily/user/UserController.java
src/main/java/com/example/tily/user/UserRequest.java
src/main/java/com/example/tily/user/UserService.java

user DTO 컨벤션 수정 및 회원가입 비밀번호 확인 로직 추가했습니다.

리팩토링 및 버그 수정
